### ISSUE TITLE
Question: How to customize header backgrounds?

### ISSUE THREAD

**Issue by frontendmonster** [mkloubert/vscode-kanban#29]
It seems impossible to change headers background via CSS
I tried this code to remove all backgrounds

```css
* {
  background-color: transparent !important;
}
```

but headers background did not change.
